WebEstoque/Controllers/MovimentoController.cs
using Entities.Entities;
using Infra.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebEstoque.Interfaces;

namespace WebEstoque.Controllers
{
    public class MovimentoController : Controller
    {
        private MovimentoEstoqueRepository _iestoqueWeb = new MovimentoEstoqueRepository();
        private readonly IEstoqueWeb iestoque;
        private readonly IFornecedorWeb _fornecedor;
        private Fornecedor _fornecedorEntity;
        public MovimentoController(IEstoqueWeb i, IFornecedorWeb fornWeb)
        {
            iestoque = i;
            _fornecedor = fornWeb;
        }

        public async Task<ActionResult> Index()
        {
            List<MovimentoEstoque> Movimento = await _iestoqueWeb.ListarEstoque_DatasEntradas_saida(1, DateTime.Now.AddMonths(-10), DateTime.Now);

            var alldates = Movimento.Select(m => m.DataMovimentacao.ToString("MM/yy"))
                                    .Distinct()
                                    .OrderBy(d => d)
                                    .ToList();

            var products = Movimento
                .GroupBy(m => m.Produto.NomeProduto)
                .Select(g => new
                {
                    NomeProduto = g.Key,
                    Quantidades = alldates.Select(date => g
                        .Where(m => m.DataMovimentacao.ToString("MM/yy") == date)
                        .Sum(m => (int?)m.Quantidade ?? 0))
                        .ToList(),
                    valorUnit = alldates.Select(date => g
                     .Where(m => m.DataMovimentacao.ToString("MM/yy") == date)
                     .Sum(m => (int?)m.ValorUnitario ?? 0)).ToList(),
                    valor = alldates.Select(date => g
                    .Where(m => m.DataMovimentacao.ToString("MM/yy") == date)
                   .Sum(m => (int?)m.ValorUnitario * m.Quantidade ?? 0)).ToList(),
                }).ToList();


            ViewBag.DadosIniciais = JsonConvert.SerializeObject(new { alldates, products });

            return View(Movimento);
        }
        
        // GET: Movimento/Create
        public ActionResult Create()
        {
            var movimentoEstoque = new MovimentoEstoque();
            return PartialView("Create", movimentoEstoque);
        }

        // POST: Movimento/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MovimentoEstoque estoque)
        {
            try
            {
                _fornecedorEntity = await _fornecedor.Select(estoque.Fornecedor.NomeFornecedor.ToLower());
                estoque.FkFornecedor = _fornecedorEntity == null ? await _fornecedor.AddFornecedor(estoque.Fornecedor.NomeFornecedor) : _fornecedorEntity.CodFornecedor;

                await iestoque.Add(estoque);

                if (estoque.notificacoes.Any())
                {
                    foreach (var item in estoque.notificacoes)
                    {
                        ModelState.AddModelError(item.nomePropriedade, item.mensagem);
                    }
                    return RedirectToAction("Index", "Home");
                }
                TempData["SuccessMessage"] = $"O Produto {estoque.Produto.NomeProduto} Foi Salvo com Sucesso !";
            }

            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                TempData["ErrorMessage"] = $"Erro ao salvar :{e.Message}";


            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Movimento/CreateSaida
        public ActionResult CreateSaida()
        {
            MovimentoEstoque model = new MovimentoEstoque();

            return PartialView("CreateSaida", model);
        }

        // POST: Movimento/CreateSaida
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateSaida(MovimentoEstoque estoque)
        {
            try
            {
                await iestoque.AddSaidaEstoque(estoque);
                if (estoque.notificacoes.Any())
                {
                    foreach (var item in estoque.notificacoes)
                    {
                        ModelState.AddModelError(item.nomePropriedade, item.mensagem);
                    }
                    TempData["SuccessMessage"] = "O Estoque foi atualizado com Sucesso!";
                    return RedirectToAction("Index", "Home");
                }
                TempData["SuccessMessage"] = $"O Produto {estoque.Produto.NomeProduto} Foi dado baixa com Sucesso!";
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                TempData["ErrorMessage"] = $"Erro ao salvar :{e.Message}";
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Movimento/Edit/5

        public async Task<ActionResult> Edit(MovimentoEstoque estoque)
        {
            var estoqueEdit = await iestoque.Select(estoque);
            return View(estoqueEdit);
        }

        // POST: ProdutosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MovimentoEstoque estoque)
        {
            try
            {
                await _iestoqueWeb.UpdateMovimentoEstoqueQuantidade(estoque);
                if (estoque.notificacoes.Any())
                {
                    foreach (var item in estoque.notificacoes)
                    {
                        ModelState.AddModelError(item.nomePropriedade, item.mensagem);
                    }

                    return View("Edit", estoque);
                }

            }
            catch
            {
                return View("Edit", estoque);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Movimento/Delete/5
        public async Task<ActionResult> Delete(int id, MovimentoEstoque estoque)
        {
            return View(await _iestoqueWeb.Select(estoque));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(MovimentoEstoque estoque)
        {
            try
            {
                var produtoDeletar = await _iestoqueWeb.Select(estoque);

                await _iestoqueWeb.DeleteMovimentoEstoque(estoque);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> TabelaMovimento()
        {
            List<MovimentoEstoque> Movimento = await iestoque.Listar();
            return View(Movimento);
        }

        [HttpGet]
        public async Task<ActionResult> ListarEstoque_DatasEntradas_saidaTabelaMov(string pesquisa, string tipo, DateTime init, DateTime fim)
        {
            List<MovimentoEstoque> Movimento = null;
            int Entrada_Saida = tipo == "Entrada" ? 1 : 2;
            Movimento = await _iestoqueWeb.ListarEstoque_DatasEntradas_saida(Entrada_Saida, init.AddDays(1), fim.AddDays(1));
            return Json(new { products = Movimento }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> ProcurarProdutoPorNome(string pesquisa)
        {
            List<MovimentoEstoque> Movimento = null;
            Movimento = await _iestoqueWeb.ProcurarPeloNome(pesquisa);

            return Json(new { products = Movimento }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> ListarEstoque_DatasEntradas_saida(string tipo, DateTime init, DateTime fim)
        {
            int Entrada_Sainda = tipo == "Entrada" ? 1 : 2;

            List<MovimentoEstoque> Movimento = await _iestoqueWeb.ListarEstoque_DatasEntradas_saida(Entrada_Sainda, init.AddDays(01), fim.AddDays(DateTime.Now.Day));

            var alldates = Movimento.Select(m => m.DataMovimentacao.ToString("MM/yy"))
                                    .Distinct()
                                    .OrderBy(d => d)
                                    .ToList();

            var products = Movimento
                .GroupBy(m => m.Produto.NomeProduto)
                .Select(g => new
                {
                    NomeProduto = g.Key,
                    Quantidades = alldates.Select(date => g
                        .Where(m => m.DataMovimentacao.ToString("MM/yy") == date)
                        .Sum(m => (int?)m.Quantidade ?? 0)).ToList(),
                    valorUnit = alldates.Select(date => g
                   .Where(m => m.DataMovimentacao.ToString("MM/yy") == date)
                    .Sum(m => (int?)m.ValorUnitario ?? 0)).ToList(),
                    valor = alldates.Select(date => g
                  .Where(m => m.DataMovimentacao.ToString("MM/yy") == date)
                 .Sum(m => (int?)m.ValorUnitario * m.Quantidade ?? 0)).ToList(),
                }).ToList();
            return Json(new { alldates, products }, JsonRequestBehavior.AllowGet);
        }
    }
}

WebEstoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:#cfcfcf">
    <nav id="sidebar" class="navbar navbar-expand-lg fixed-top d-flex flex-column h-100 col-md-4" style="width: 250px; background: radial-gradient(circle, rgba(187,0,0,0.961) 0%, rgba(45,54,62,0.989) 0%);">
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="navbar-nav me-auto mb-2 mb-lg-0 d-flex h-100 justify-content-around flex-column pt-5 ">
                <div class="nav-item text-center col-md-12">
                    <h3>@Html.ActionLink("Estoque", "Index", "Home", null, new { @class = "nav-link pb-3 text-white", Styles = "font-size:25px" })</h3>
                    <hr class="text-white" />
                </div>
                <div class="btn-group dropright">
                    <a class="nav-link dropdown-toggle w-100 text-white text-center" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:25px">
                        Cadastro
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <div class="text-center sub" data-bs-toggle="modal" data-bs-target="#editModal" data-url="@Url.Action("Create", "Movimento")">Registrar Entrada</div>
                        <div class="text-center sub" data-bs-toggle="modal" data-bs-target="#edit" data-url="@Url.Action("CreateSaida", "Movimento")">Entrega de Materiais</div>
                    </div>
                    <hr class="text-white" />
                </div>

                <div class="btn-group dropright">
                    <a class="nav-link dropdown-toggle w-100 text-white text-center" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:25px">
                        DashBoard
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        @Html.ActionLink("Comparativo Mês a Mês sobre o valor", "Index", "Movimento", null, new { @class = "dropdown-item Dash" })
                        @Html.ActionLink("Comparativo Entre dois meses sobre o valor", "Index", "Movimento", null, new { @class = "dropdown-item Dash" })
                        @Html.ActionLink("Comparativo Mês a Mês sobre a Quantidade", "Index", "Movimento", null, new { @class = "dropdown-item Dash" })
                        @Html.ActionLink("Comparativo Entre dois meses sobre a Quantidade", "CreateSaida", "Movimento", null, new { @class = "dropdown-item Dash" })
                        @Html.ActionLink("Todos", "CreateSaida", "Movimento", null, new { @class = "dropdown-item Dash" })
                        @Html.ActionLink("Histórico do Estoque", "TabelaMovimento", "Movimento", null, new { @class = "dropdown-item Dash" })
                    </div>
                    <hr class="text-white" />
                </div>

                <div></div>
            </div>
        </div>
    </nav>
    <nav style="background: radial-gradient(circle, rgba(187,0,0,0.961) 0%, rgba(91,139,187,0.989) 0%);" class="navbar navbar-expand-lg fixed-top">
        <div class="col-md-12">
            <button class="navbar-toggler text-left" type="button" onclick="toggleSidebar()" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-band text-white d-flex justify-content-between">
                <h3 style="padding-left:2%" class="" id="Titulo">EstoqueControler</h3>
                <div class="fa-solid fa-hand-holding-dollar align-content-end p-2"></div>
            </div>
        </div>
    </nav>

    <div class="col-md-12" style="margin-top:20px;padding-left:260px;" id="sid">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>


    <script>
        function toggleSidebar() {
            var sidebar = document.getElementById('sidebar');
            // Alterna a classe d-none
            sidebar.classList.toggle('d-none'); // Usa a classe d-none do Bootstrap para ocultar/mostrar
        }

        // Adicionando evento de ajuste automático da barra lateral
        window.addEventListener('resize', function () {
            var sidebar = document.getElementById('sidebar');
            var nav = document.getElementById('navbarNav');
            var sid = document.getElementById('sid');
            var titulo = document.getElementById('Titulo');
            if (window.innerWidth >= 768) {
                sidebar.classList.remove('d-none'); // Garante que a barra lateral apareça em telas maiores
                nav.style = "display:block";
                sid.style = "margin-left: 250px;"
                titulo.style = "padding-left: 2%";
            } else {
                sidebar.classList.add('d-none'); // Garante que a barra lateral esteja oculta em telas menores
                sid.style = "margin-left: 0px;"
                nav.style = "display:block";
                titulo.style = "padding-left: 20%";
            }
        });

        // Fechar a barra lateral ao carregar a página em telas menores
        window.onload = function () {
            if (window.innerWidth < 768) {
                document.getElementById('sidebar').classList.add('d-none'); // Inicia com a barra lateral oculta em telas menores
                sid.style = "margin-left: 0px;"
                nav.style = "display:block";
                titulo.style = "padding-left: 20%";
            }
        };

    </script>

    <style>
        .sub:hover {
            cursor: pointer;
            background-color: #466b8b;
            color: white;
            font-size: 19px;
        }

        #sidebar {
            transition: all 0.3s ease;
        }

        .Dash:hover {
            cursor: pointer;
            background-color: #466b8b;
            color: white;
            font-size: 19px;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>
</html>